services:
  - type: web
    name: kids-audio-app
    plan: free
    env: python
    rootDir: kidswebapp
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --chdir backend"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MONGO_URI
        generateValue: true
      - key: DB_NAME
        value: "kids_audio_app"
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20.11.1"
